build: root runClient alias für Mod-Menu-Devstart
-
> Configure project :1.21.11
Fabric Loom: 1.14.6

> Configure project :1.21.4
Fabric Loom: 1.14.6

> Task :1.21.11:checkKotlinGradlePluginConfigurationErrors SKIPPED
> Task :1.21.11:compileKotlin UP-TO-DATE
> Task :1.21.11:compileJava UP-TO-DATE
> Task :1.21.11:processResources UP-TO-DATE
> Task :1.21.11:classes UP-TO-DATE
> Task :1.21.11:generateLog4jConfig UP-TO-DATE
> Task :1.21.11:generateRemapClasspath UP-TO-DATE
> Task :1.21.11:generateDLIConfig
> Task :1.21.11:configureLaunch
> Task :1.21.11:downloadAssets
> Task :1.21.11:configureClientLaunch

> Task :1.21.11:runClient
[34m[22:58:11][m [32m[main/INFO][m [36m(FabricLoader/GameProvider)[m [0mLoading Minecraft 1.21.11 with Fabric Loader 0.18.5
[m[34m[22:58:11][m [33m[main/WARN][m [36m(FabricLoader/Resolution)[m [0mMod resolution failed
[m[34m[22:58:11][m [32m[main/INFO][m [36m(FabricLoader/Resolution)[m [0mImmediate reason: [HARD_DEP_INCOMPATIBLE_PRESELECTED modmenu 14.0.0 {depends minecraft @ [>=1.21.5 <1.21.6]}, ROOT_FORCELOAD_SINGLE modmenu 14.0.0]
[m[34m[22:58:11][m [32m[main/INFO][m [36m(FabricLoader/Resolution)[m [0mReason: [HARD_DEP modmenu 14.0.0 {depends minecraft @ [>=1.21.5 <1.21.6]}]
[m[34m[22:58:11][m [32m[main/INFO][m [36m(FabricLoader/Resolution)[m [0mFix: add [], remove [], replace [[modmenu 14.0.0] -> add:modmenu 1 ([(-∞,∞)])]
[m[34m[22:58:11][m [31m[main/ERROR][m [36m(FabricLoader)[m [31mIncompatible mods found!
[m
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Mod Menu' (modmenu) 14.0.0 with any version that is compatible with:
		 - minecraft 1.21.11
More details:
	 - Mod 'Mod Menu' (modmenu) 14.0.0 requires any version between 1.21.5 (inclusive) and 1.21.6 (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.11!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:202)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:66)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

> Task :1.21.11:runClient FAILED

[Incubating] Problems report is available at: file:///home/thomas/git-projects/Visotaris%20OPMod/build/reports/problems/problems-report.html

Deprecated Gradle features were used in this build, making it incompatible with Gradle 10.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/9.4.0/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
8 actionable tasks: 3 executed, 5 up-to-date startet jetzt gezielt MC 1.21.11
- keine parallelen Starts von 1.21.4 + 1.21.11 mehr
- zusätzliche Komfort-Tasks: runClient1214 / runClient12111